- hosts: worker
  become: yes
  pre_tasks:
    - name: uninstall apache2
      apt: name=apache2 state=absent
  roles:
    - { role: php7.2 }
    - { role: nginx }
    - { role: git }
    - { role: composer }
  vars:
    proxy_env: 'http://ITS-552131-cb09f:6aea3@proxy.its.ac.id:8080'
    sites: hackathon
    user_git: rohanaq
    path_to_app: /var/www/hackathon

- hosts: db
  become: yes
  become_user: root
  become_method: su
  vars:
    proxy_env: 'http://ITS-552131-cb09f:6aea3@proxy.its.ac.id:8080'
    username: 'regal'
    password: 'bolaubi'
  roles:
    - { role: db }