- hosts: worker
  become: yes
  pre_tasks:
    - name: uninstall apache2
      apt: name=apache2 state=absent

  roles:
    - { role: php7.2 }
    - { role: nginx }
    - { role: git }
    - { role: composer }

  vars:
    sites: hackathon
    user_git: cakthe
    path_to_app: /var/www/hackathon
