- name: Add PHP repository
  apt_repository: repo='ppa:ondrej/php'
  notify:
  - update repo

- name: Install php7.2
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - php7.2
    - php7.2-cgi
    - php7.2-cli
    - php7.2-common
    - php7.2-curl
    - php7.2-fpm
    - php7.2-gd
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-xml
    - php7.2-zip
  notify:
    - restart php-fpm
