version: '3'

services:
  worker1:
    depends_on:
      - db
    image: reservasi
    restart: always
    environment:
      DB_HOST: 172.20.0.25
      DB_USERNAME: userawan
      DB_PASSWORD: buayakecil
      DB_NAME: reservasi
    networks:
      docker1:
        ipv4_address: 172.20.0.24
  
  worker2:
    depends_on:
      - db
    image: reservasi
    restart: always
    environment:
      DB_HOST: 172.20.0.25
      DB_USERNAME: userawan
      DB_PASSWORD: buayakecil
      DB_NAME: reservasi
    networks:
      docker1:
        ipv4_address: 172.20.0.23
  
  worker3:
    depends_on:
      - db
    image: reservasi
    restart: always
    environment:
      DB_HOST: 172.20.0.25
      DB_USERNAME: userawan
      DB_PASSWORD: buayakecil
      DB_NAME: reservasi
    networks:
      docker1:
        ipv4_address: 172.20.0.22

  load_balancer:
    image: nginx:stable-alpine
    depends_on:
      - worker1
      - worker2
      - worker3
    ports:
      - 7777:80
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      docker1:
        ipv4_address: 172.20.0.21

  db:
    image: mysql_reservasi
    restart: always
    networks:
      docker1:
        ipv4_address: 172.20.0.25

volumes:
  reservasi:

networks:
  docker1:
    ipam:
      config:
        - subnet: 172.20.0.0/24
