version: '3'

services:
  flask:
    depends_on:
      - db
    image: reservasi
    volumes:
      - reservasi:/var/www/reservasi
    restart: always
    environment:
      DB_HOST: 172.20.0.25:3306
      DB_USERNAME: userawan
      DB_PASSWORD: buayakecil
      DB_NAME: reservasi
    networks:
      docker1:
        ipv4_address: 172.20.0.24

  db:
    image: mysql_reservasi
#    volumes:
#      - "reservasi:/var/www/reservasi"
    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: xyz
#      MYSQL_USER: userawan
#      MYSQL_PASSWORD: buayakecil
#      MYSQL_DATABASE: reservasi
    networks:
      docker1:
        ipv4_address: 172.20.0.25

volumes:
  reservasi:

networks:
  docker1:
    ipam:
      config:
        - subnet: 172.20.0.0/24
