version: '3'

services:
  flask:
    depends_on:
      - db
    image: reservasi
    restart: always
    environment:
      DB_HOST: 172.20.0.25
      DB_USERNAME: userawan
      DB_PASSWORD: buayakecil
      DB_NAME: reservasi
    networks:
      docker1:
        ipv4_address: 172.20.0.24

  db:
    image: mysql_reservasi
    restart: always
    networks:
      docker1:
        ipv4_address: 172.20.0.25

volumes:
  reservasi:

networks:
  docker1:
    ipam:
      config:
        - subnet: 172.20.0.0/24
